// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetProviderConfigReference of this ClusterProviderConfigUsage.
func (p *ClusterProviderConfigUsage) GetProviderConfigReference() xpv2.ProviderConfigReference {
	return p.ProviderConfigReference
}

// GetResourceReference of this ClusterProviderConfigUsage.
func (p *ClusterProviderConfigUsage) GetResourceReference() xpv2.TypedReference {
	return p.ResourceReference
}

// SetProviderConfigReference of this ClusterProviderConfigUsage.
func (p *ClusterProviderConfigUsage) SetProviderConfigReference(r xpv2.ProviderConfigReference) {
	p.ProviderConfigReference = r
}

// SetResourceReference of this ClusterProviderConfigUsage.
func (p *ClusterProviderConfigUsage) SetResourceReference(r xpv2.TypedReference) {
	p.ResourceReference = r
}

// GetProviderConfigReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) GetProviderConfigReference() xpv2.ProviderConfigReference {
	return p.ProviderConfigReference
}

// GetResourceReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) GetResourceReference() xpv2.TypedReference {
	return p.ResourceReference
}

// SetProviderConfigReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) SetProviderConfigReference(r xpv2.ProviderConfigReference) {
	p.ProviderConfigReference = r
}

// SetResourceReference of this ProviderConfigUsage.
func (p *ProviderConfigUsage) SetResourceReference(r xpv2.TypedReference) {
	p.ResourceReference = r
}
